### ISSUE TITLE
Remote driver URL cannot be passed via command line

### ISSUE THREAD

**Issue by MazeChaZer** [LearnLib/alex#65]
Minimal example:

```yml
version: '3.7'
services:
    alex:
        image: learnlib/alex:unstable
        ports:
            - 8000:8000
        command: java -jar /usr/share/java/alex/alex.war --ltsmin.path=/opt/ltsmin/bin --remoteDriver=http://selenium-hub:4444/wd/hub
```

This should configure the path to the Selenium remote driver, but if one opens `http://localhost:8000` in the browser and goes into settings, the text input field for this option is just empty.

Previoiusly, even environment variables worked:

```yml
version: '3.7'
services:
    alex:
        image: learnlib/alex:unstable
        environment:
            remoteDriver: http://selenium-hub:4444/wd/hub
        ports:
            - 8000:8000
```

It would be great if that was possible again, too, so that the whole command doesn't have to be copied from the Dockerfile into the docker-compose.yml.
